<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 11px;
            color: #1e293b;
            background: #fff;
        }

        .top-bar {
            background: #0f172a;
            height: 5px;
            width: 100%;
        }

        .header {
            padding: 20px 28px 16px 28px;
            border-bottom: 1px solid #e2e8f0;
            background: #f8fafc;
        }

        .org-name {
            font-size: 17px;
            font-weight: 800;
            color: #0f172a;
        }

        .report-title {
            font-size: 13px;
            color: #475569;
            margin-top: 2px;
        }

        .meta {
            font-size: 10px;
            color: #94a3b8;
            margin-top: 6px;
        }

        .content {
            padding: 20px 28px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        thead th {
            background: #0f172a;
            color: #fff;
            text-align: left;
            font-size: 10px;
            text-transform: uppercase;
            letter-spacing: 0.03em;
            padding: 8px 10px;
        }

        tbody td {
            padding: 7px 10px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 11px;
        }

        tbody tr:nth-child(even) {
            background: #f8fafc;
        }

        .num {
            text-align: right;
        }

        .positive { color: #16a34a; font-weight: 700; }
        .negative { color: #dc2626; font-weight: 700; }
        .muted { color: #94a3b8; }

        .footer {
            padding: 14px 28px;
            border-top: 1px solid #e2e8f0;
            font-size: 9px;
            color: #94a3b8;
        }
    </style>
</head>
<body>
<div class="top-bar"></div>

<div class="header">
    <div class="org-name">{{ $data['orgName'] ?? 'Organization' }}</div>
    <div class="report-title">{{ $data['title'] }}</div>
    <div class="meta">Year: {{ $data['year'] }} &middot; Generated: {{ $data['date'] }}</div>
</div>

<div class="content">
    <table>
        <thead>
        <tr>
            <th>Employee</th>
            <th>Department</th>
            <th>Leave Type</th>
            <th class="num">Entitled</th>
            <th class="num">Used</th>
            <th class="num">Pending</th>
            <th class="num">Remaining</th>
        </tr>
        </thead>
        <tbody>
        @forelse($data['rows'] as $row)
            <tr>
                <td>{{ $row['employee_name'] }}</td>
                <td>{{ $row['department'] ?? '-' }}</td>
                <td>{{ $row['leave_type_name'] }}</td>
                <td class="num">{{ $row['entitled_days'] ?? 'Unlimited' }}</td>
                <td class="num">{{ $row['used_days'] }}</td>
                <td class="num">{{ $row['pending_days'] }}</td>
                <td class="num {{ $row['remaining_days'] === null ? 'muted' : ($row['remaining_days'] < 0 ? 'negative' : 'positive') }}">
                    {{ $row['remaining_days'] ?? 'Unlimited' }}
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="7" style="text-align:center; color:#94a3b8; padding:24px;">No records found.</td>
            </tr>
        @endforelse
        </tbody>
    </table>
</div>

<div class="footer">
    Generated by Soja TA &middot; {{ $data['date'] }}
</div>
</body>
</html>
