<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {

        Schema::create('devices', function (Blueprint $table) {
            $table->id();
            $table->string('device_name');
            $table->foreignId('organization_id')->constrained()->cascadeOnDelete();
            $table->string('platform')->nullable(); // e.g., Android, iOS
            $table->string('checkpoint_id')->unique(); // autogenerated device code
            $table->string('pin', 10)->nullable();     // optional PIN
            $table->foreignId('device_location_id')->constrained('device_locations')->cascadeOnDelete();
            $table->boolean('active')->default(true);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('devices');
    }
};
